### ISSUE TITLE
Configuration service

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#312]
# Problem
Currently flists and probably other settings are hardcoded in the AYS'ses creating a versioning problem. Cause we cannot create reproducable environments anymore.

# Solution
We introduce a **Configuration** AYS holding a key value store we can fill with all sorts of settings. The AYS'ses that need some sort of configuration settings, eg for flists, supported jumpscale version, zero-os core0 version, ..., can then consume the **Configuration** AYS to read there configuration values.

# Implementation
AYS'ses that depend on these configuration settings need to fetch the values from the **Configuration** AYS. If the setting they are looking for is not present, they can fallback on a hardcoded value (eg latest version)

# Apply to
- jumpscale version: Check the jumpscale version installed in each AYS init action.
- zero-os 0-core version: Bootstrap service should check the version of the 0-core before adding it.
- all used flists

# Note
**Don't forget to add the necessary documentation**

**Comment by Dinaamagdy** [comment]
### when I use configuration blueprint with js version 8.2 and ays was running in js9 doesn't give any error or crash 
#### blueprint : 
```
configuration__main:
  configurations:
  - key: '0-core-version'
    value: 'master'
  - key: 'js-version'
    value: '8.2'
  - key: 'gw-flist'
    value: 'https://hub.gig.tech/gig-official-apps/zero-os-gw-1.1.0-alpha-3.flist'
  - key: 'ovs-flist'
    value: 'https://hub.gig.tech/gig-official-apps/ovs-1.1.0-alpha-3.flist'
  - key: '0-disk-flist'
    value: 'https://hub.gig.tech/gig-official-apps/0-disk-1.1.0-alpha-3.flist'
```
